id: A4B7A3867
title: A Short Practice for Averting Obstacles through Vajrakīla
type: translation
pechas:
- I9BD80B72
- I0C276155
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:58.428891
  last_modified_at: 2023-01-04 11:51:58.428905
  collections:
  - Fifth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I9BD80B72/A284: 869A
  I0C276155/40D6: 869A
